server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: ${PORT}
spring:
  profiles:
    active:
      - prod
  datasource:
    url: jdbc:mysql://${RDS.HOSTNAME}:${RDS.PORT}/${RDS.DBNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS.USERNAME}
    password: ${RDS.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
security:
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE.CLIENT}
          client-name: google
          client-secret: ${GOOGLE.SECRET}
          client-authentication-method: ${CLIENT.METHOD}
          authorization-grant-type: ${CLIENT.TYPE}
          redirect-uri: ${GOOGLE.REDIRECT}
          scope: ${GOOGLE.SCOPE}
        kakao:
          client-id: ${KAKAO.CLIENT}
          client-name: kakao
          client-secret: ${KAKAO.SECRET}
          client-authentication-method: ${CLIENT.METHOD}
          authorization-grant-type: ${CLIENT.TYPE}
          redirect-uri: ${KAKAO.REDIRECT}
          scope: ${KAKAO.SCOPE}
        naver:
          client-id: ${NAVER.CLIENT}
          client-name: naver
          client-secret: ${NAVER.SECRET}
          client-authentication-method: ${CLIENT.METHOD}
          authorization-grant-type: ${CLIENT.TYPE}
          redirect-uri: ${NAVER.REDIRECT}
          scope: ${NAVER.SCOPE}
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
          token-uri: https://oauth2.googleapis.com/token
          user-info-uri: https://www.googleapis.com/userinfo/v2/me



cloud:
  aws:
    s3:
      bucket: ${S3.BUCKET}
      domain: ${S3.DOMAIN}
    credentials:
      access-key: ${S3.ACCESSKEY}
      secret-key: ${S3.SECRETKEY}
    region:
      static: ${S3.REGION}
      auto: false
    stack:
      auto: false

my-env:
  jwt:
    key: ${JWT.KEY}
  chrome-driver:
    path: /usr/local/bin/chromedriver/chromedriver

logging:
  level:
    com.example.baseballprediction: DEBUG